name: debug


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
        sudo apt-get install -y libkrb5-dev
      continue-on-error: true


    - name: Install dependencies
      run: yarn install

    - name: Build VSCode
      run: yarn run gulp vscode-win32-x64
      continue-on-error: true
    - name: cout dir
      run: dir
      continue-on-error: true
    - name: zip
      run: zip -r theout.zip ../123IDE/
      continue-on-error: true
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: vscode-x64-build
        path: ./theout.zip
