name: Build x64 VSCode

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  winbuild:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
          New-Item -ItemType Directory -Path "tempbuild"
          Get-ChildItem -Exclude "tempbuild" | Move-Item -Destination "tempbuild"
          cd tempbuild
          yarn install
          npm install --global gulp-cli
          gulp vscode-win32-x64
          cd ..

    - name: tar
      run: tar -czf theout.tar.gz ./VSCode-win32-x64

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: vscode-x64-build
        path: ./theout.tar.gz
